### ISSUE TITLE
好书推荐

### ISSUE THREAD

**Issue by Gusabary** [MingCheng991129/learngit#1]
Git Book 良心入门教程 墙裂推荐
1, 2, 3, 7, 10 章 不用谢我（
https://git-scm.com/book/zh/v2

**Comment by MingCheng991129** [comment]
> Git Book 良心入门教程 墙裂推荐
> 1, 2, 3, 7, 10 章 不用谢我（
> https://git-scm.com/book/zh/v2

我参考的这个教程写的也很好，但是写的没那么细：https://www.liaoxuefeng.com/wiki/896043488029600
